#ifndef CMN_H
#define CMN_H

#include <tonc.h>

// These files are autogenerated from the file in the graphics folder
#include "spritemap.h"
#include "bg.h"

extern u32 timer_last;
extern u32 timer;
#define TIMER(c) ((timer & (c)) != 0 && ((timer_last & (c)) == 0))

enum SCENE {
  SCENE_START = -1,
  SCENE_MENU = 0,
  SCENE_GAME = 1,
};

extern enum SCENE scene;
extern enum SCENE old_scene;

void scroll_bg(void);

#endif /* CMN_H */
